name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      # allow the action to create a deployment on pages
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Determine publish directory
        id: publish_dir
        run: |
          # The React Router v7 static build places client assets under build/client
          if [ -d "build/client" ]; then echo "publish_dir=build/client" >>$GITHUB_OUTPUT; exit 0; fi
          if [ -d "build" ]; then echo "publish_dir=build" >>$GITHUB_OUTPUT; exit 0; fi
          # fallback to dist for other toolchains
          if [ -d "dist" ]; then echo "publish_dir=dist" >>$GITHUB_OUTPUT; exit 0; fi
          echo "No publish directory found" >&2
          exit 1

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ''
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ steps.publish_dir.outputs.publish_dir }}
          # If you want the site to be published to a branch other than gh-pages,
          # set publish_branch: 'gh-pages' (default) or 'master' if repo is user site.
          # By default this action will create/update the 'gh-pages' branch.
